trigger:
 - main

pool:
  name: 'Default'

variables:
   imageName: 'pipelines-javascript-docker'

steps:
- task: AzureContainerApps@1
  inputs:
    appSourcePath: 'app/'
    azureSubscription: 'rgconn'
    acrName: 'mytesdockregistry'
    acrUsername: 'mytesdockregistry'
    acrPassword: 'trFBbNSbNy5JIF98gT29OKmmjiePz2zY8LriEys5r8+ACRB3J/f/'
    dockerfilePath: 'Dockerfile'
    imageToBuild: 'mytesdockregistry.azurecr.io/sample/app:latest'
    imageToDeploy: 'mytesdockregistry.azurecr.io/sample/app:latest'
    containerAppName: 'sample-app'
    resourceGroup: 'myRG'
    containerAppEnvironment: 'managedEnvironment-myRG-a6a8'
    targetPort: '80'
    location: 'EAST US'
# - task: Docker@2
#   inputs:
#     containerRegistry: 'acrconn'
#     repository: $(imageName)
#     command: 'buildAndPush'
#     Dockerfile: '**/Dockerfile'
#     tags: 'latest'


# - script: |
#    docker login testdockrregistry.azurecr.io -u testdockrregistry -p 2SJb5z90nnEIsdjRgOQGZZZxY7sCEvOc/xQ3nseT2r+ACRBMOyq9
#    docker pull testdockrregistry.azurecr.io/$(imageName)
#    docker run -d -p 80:80 testdockrregistry.azurecr.io/$(imageName)
#   displayName: 'Command Line Script'



