trigger:

 - main

pool:
  name: 'test pool'
  vmImage: 'ubuntu-latest' 

variables:
   imageName: 'pipelines-javascript-docker'

steps:
- task: CmdLine@2
  inputs:
    script: |
      sudo apt-get update
      sudo apt-get install ca-certificates curl gnup
      curl -fsSL https://get.docker.com -o get-docker.sh
      sudo sh ./get-docker.sh
      sudo groupadd docker
      sudo usermod -aG docker ${USER}

- task: Docker@2
  displayName: Build an image
  inputs:
    repository: $(imageName)
    command: build
    Dockerfile: app/Dockerfile
